name: Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task-1
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24" # Can also use 'latest'

      - name: Install dependencies
        run: npm install # npm clean install

      - name: Run Linter
        run: npm run lint

      - name: Run Unit Tests
        run: npm test # Run vitest tests (defined in package.json

      - name: Build the React application
        run: npm run build
